#!/bin/bash
#random

apt install jq curl -y

rm -rf /root/xray/scdomain
rm -rf /root/xray/flare-domain
mkdir -p /root/xray
clear

sub=$(</dev/urandom tr -dc a-z0-9 | head -c5)

DOMAIN=hscript2.my.id
WS_DOMAIN=ws-${sub}.hscript2.my.id
FLARE_DOMAIN=flare-${sub}.hscript2.my.id
NS_DOMAIN=ns-${sub}.hscript2.my.id

CF_TOKEN="ZJ-HMdxrRwq54Mpv7NbuNlqOW11SaXIKQRQBqLLa"

set -euo pipefail

IP=$(curl -sS ifconfig.me)

echo "Updating DNS for ${WS_DOMAIN}..."

ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" | jq -r .result[0].id)

RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${WS_DOMAIN}" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#RECORD}" -le 10 ]]; then
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${WS_DOMAIN}'","content":"'${IP}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi

echo "Updating DNS FLARE for ${FLARE_DOMAIN}..."

RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" \
--data '{"type":"CNAME","name":"'${FLARE_DOMAIN}'","content":"'${WS_DOMAIN}'","ttl":120,"proxied":true}' | jq -r .result.id)

curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${WS_DOMAIN}'","content":"'${IP}'","ttl":120,"proxied":false}' > /dev/null

echo "Updating DNS NS for ${NS_DOMAIN}..."

RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#RECORD}" -le 10 ]]; then
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" \
--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${WS_DOMAIN}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi

curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
-H "Authorization: Bearer ${CF_TOKEN}" \
-H "Content-Type: application/json" \
--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${WS_DOMAIN}'","ttl":120,"proxied":false}' > /dev/null

echo "Host WS : $WS_DOMAIN"
echo "Host FLARE: $FLARE_DOMAIN"
echo "Host NS : $NS_DOMAIN"

echo $FLARE_DOMAIN >> /root/xray/flare-domain
echo $NS_DOMAIN >> /root/nsdomain
echo $WS_DOMAIN >> /root/domain
echo $FLARE_DOMAIN >> /etc/xray/flare-domain
echo $WS_DOMAIN >> /etc/xray/domain
echo $WS_DOMAIN >> /root/scdomain
echo $WS_DOMAIN >> /root/xray/scdomain

echo -e "Done Record Domain= $WS_DOMAIN"
echo -e "Done Record Flare Domain= $FLARE_DOMAIN"
echo -e "Done Record NSDomain= $NS_DOMAIN"

sleep 1
